version: 0.2

phases:
  install:
    commands:
      - npm cache verify
      - npm install

  build:
    commands:
      - npm run build
      - aws s3 sync s3://portfoliobuildartifact/portfolioEC2/build/ s3://myportfolioreact2/ --region ap-south-2

artifacts:
  files: '**/build/*'
