version: 0.2

phases:
  install:
    commands:
      - npm cache clean --force
      - npm cache verify
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files: '**/build/*'
